### ISSUE TITLE
compilation error curl

### ISSUE THREAD

**Issue by njscorpion** [ZerBea/hcxtools#102]
i am using Kali Linux "4.19.0-kali5-amd64"

> lsb_release -a:
> No LSB modules are available.
> Distributor ID:	Kali
> Description:	Kali GNU/Linux Rolling
> Release:	2019.2
> Codename:	n/a

while trying  to install libcurl3

i am getting :

> Package libcurl3 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   libcurl4
> 
> E: Package 'libcurl3' has no installation candidate

I have the latest libcurl4 is there a workaround?

**Comment by ZerBea** [comment]
You don't need libcurl3, but you need the dev files to compile hcxtools.
From README.md:
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'

See KALI package tracker:
https://pkg.kali.org/pkg/curl

Also explained for example here:
https://github.com/ZerBea/hcxtools/issues/67

BTW:
Closed this issue, because it isn't related to hcxtools.
But you can still ask questions here or in ifficial KALI forum:
https://forums.kali.org/

**Comment by njscorpion** [comment]
thanks i am sorry it was also mention in the read me

**Comment by ZerBea** [comment]
No problem.
KALI is designed to be used by penetration testers and for coder or user who compile code.
So only a few development packages (dev) are included and you must(!) install the other ones by yourself. That is the philosophy of KALI (Debian, Ubuntu, Mint, ... - the list is long) and just another good reason why I use and recommend Arch Linux.

**Comment by ih8github** [comment]
@njscorpion did you get it to work?

I have a similar error on Kali. hcxtools can’t find curl. Curl works fine. So trying to install the libcurl4-OpenSSL-dev you get a message that it requires an old (7.58) version of libcurl4 that would breal every other major app in Kali...

**Comment by ZerBea** [comment]
That is an issue of KALI and you should ask there.
Please read this:
https://github.com/ZerBea/hcxtools/issues/153#issuecomment-660688113
