### ISSUE TITLE
not able to install hcxpcaptools

### ISSUE THREAD

**Issue by vipulsarode** [ZerBea/hcxtools#104]
when i try to install the requirements of tools that is apt install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev it shows error. 

E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is an other process using it?

**Comment by ZerBea** [comment]
I assume you tried it as super user: sudo apt install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev

If you can't get a lock, another process is (still) running to upgrade your system or a previous system upgrade is broken. How to solve it, depends on your distribution.
Please read more here:
https://askubuntu.com/questions/15433/unable-to-lock-the-administration-directory-var-lib-dpkg-is-another-process

or here:
https://askubuntu.com/questions/1109982/e-could-not-get-lock-var-lib-dpkg-lock-frontend-open-11-resource-temporari

or here:
https://ourcodeworld.com/articles/read/824/how-to-solve-kali-linux-cli-error-could-not-get-lock-var-lib-dpkg-lock-open-9-resource-temporarily-unavailable

a video about this issue is here:
https://www.youtube.com/watch?v=kjgE-111XIY

BTW:
Closed this issue, because it is not related to hcxtools.
But you can ask questions still here.
