### ISSUE TITLE
Compilation Terminated 

### ISSUE THREAD

**Issue by AibelKingslayer** [ZerBea/hcxtools#108]
curl/curl.h no such file or directory fatal error
im using kali linux 2019.3

**Comment by ZerBea** [comment]
Unsolved dependency. From README.md:
Requirements
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)

To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'

Closed, because this issue is not related to hcxtools.
