### ISSUE TITLE
hcxdumptool cant find any pmkids

### ISSUE THREAD

**Issue by hcxtoolhelp** [ZerBea/hcxtools#116]
When I run the hcxdumptool after the line with the numbers on it (dumped, powned) nothing else happens. sometimes it says there is an eacom handshake timeout. please help

**Comment by ZerBea** [comment]
To answer I need more information, because your question is a little bit confusing.
Please add your complete command line
$ hcdumptool .........
Please add output of:
$ hcxdumptool -I
( to determine the driver)
and
$ hcxdumptool -i "your interface" --check_driver
( to determine that the driver support full monitor mode and nothing interferes hcxdumptool))
and
$ hcxdumptool -i "your interface" --do_rcascan
(run this command for 2 minutes - to determine that the driver support full packet injection - we only need the status output)

**Comment by hcxtoolhelp** [comment]
OK thank you for helping me I am sorry for not specific I do not use Linux a lot :D 
My command $ hcxdumptool -i wlan0mon  -o filenamed.pcapng --enable_status=1 
OUTPUT:
initialization...
warning: wlan0mon is probably a monitor interface
interface is already in monitor mode

start capturing (stop with ctrl+c)
INTERFACE................: wlan0mon
ERRORMAX..............: 100 errors
FILTERLIST.................: 0 entries
BEACONLIST............: 0 entries
MAC CLIENT............: aabbccddeeff
MAC ACCESS POINT: aabbccddeeff (incremented on every new client)
EAPOL TIMEOUT...: 150000
REPLAYCOUNT.......: 62049
SNONCE...................: a lot of characters
ANONCE..................: a lot of characters

[17:10:20 - 011] aabbccddeeff -> aabbccddeeff .. [HANDSHAKE AP-LESS, EAPOL TIMEOUT 10120]
[17:10:20 - 011] aabbccddeeff -> aabbccddeeff .. [HANDSHAKE AP-LESS, EAPOL TIMEOUT 10120]

**Comment by hcxtoolhelp** [comment]
hcxdumptool -I

wlan interfaces:
aabbccddeeff wlan0mon (rt73usb) warning: probably a monitor interface!


hcxdumptool -i wlan0mon --check_driver

starting driver test...
interface is already in monitor mode - we skip some tests
driver tests passed - all required iotcl() system calls are supporte by driver
restoring old driver settings


hcxdumptool -i wlan0mon --do_rcascan

initialization...
warning: wlan0mon is probably a monitor interface
interface is already in monitor mode

[17:23:35] aabbccddeeff "ap name 1" [CHANNEL 1, AP IN RANGE]
[17:23:35] aabbccddeeff "ap name 1" [CHANNEL 1, AP IN RANGE]

**Comment by hcxtoolhelp** [comment]
my problem is that no matter how long i let my command run for it never seems to find any pmkids

**Comment by ZerBea** [comment]
First of all: I'll close this issue, because hcxdumptool is working like expected. Regarding the output, there is no issue. You can still ask your questions here.

The driver ((rt73usb)) support monitor mode and full packet injection.
hcxdumptool is working like expected (APs IN RANGE).
Unfortunately none of the APs in your range use a PMKID. So hcxdumptool can't request it.

BTW:
you're running hcxdumptool not(!) on its own monitor mode. Instead you are using a monitor mode, (wlan0mon) set by a third party tool:
warning: wlan0mon is probably a monitor interface

I assume you use airmon-ng.
There is absolute no need to do this and you should use hcxdumptool's own monitor mode.
If you start hcxdumptool on the physical interface (wlan0) it will tell you what possible could interfere. Then stop this tasks:
systemctl stop .......
and run hcxdumptool again on physical interface (wlan0).
