### ISSUE TITLE
hcxpcapngtool: evaluate Iinformation Element (IE) to retrieve more information about AP hardware 

### ISSUE THREAD

**Issue by ChemicalNRG** [ZerBea/hcxtools#120]
I get an error with hcxmactool and -a (vendor) and pmkidin
error is "Segmentation fault"

When using it with hccapxin everything seems to be ok, but what i did notice is that file size compared with wlanhcx2ssid -V with the same .hccapx file is very different but the same records are written if i can beleave stdout. 3144 for file using wlanhcx2ssid -V and 1572 for file using hcxmactool -a.

The files (.16800 & .hccapx) were made with hcxdumptool --> hcxpcaptool --prefix-out

Also i do have 3 requests, but dont know if it is already in you tools.
1.     I would like a hcxtools --help so i can see what all tools do without having to go to the github page.
2.     An option in hcxmactool to export pmkid & hccapx in all vendor files without having to enter a specific vendor name.
3.     An option in hcxpcaptool to have a prefix name so we can choose which options we want, but dont need to enter the name of each option.

**Comment by ZerBea** [comment]
There will be no version 5.x.x. Hash modes 2500, 2501, 16800 and 16801 are deprecated and will be replaced by hash mode 22000 and 22001. HCCAPX and PMKID hash files are deprecated, too.

When hashcat v.6.0.0 is released
  22000 | WPA-PBKDF2-PMKID+EAPOL                           | Network Protocols
  22001 | WPA-PMK-PMKID+EAPOL                              | Network Protocols

This, new hcxtools will replace the old 250x/16801 versions.
hcxpcapngtool | Provide new hashcat format 22000 - highly experimental - format may change until final release (see changelog)
-- | --
hcxpsktool | Calculates candidates for hashcat and john based on based on hcxpcaptool output (-c -o, -z- -U) or commandline input
hcxhashtool | Provide various filter operations on new PMKID/EAPOL hash line - highly experimental - only limited functions
hcxwltool | Calculates candidates for hashcat and john based on hcxpcaptool output (-E, -I- -U)
hcxhash2cap | Converts hash file (PMKID, EAPOL-hccapx, EAPOL-hccap, WPAPSK-john) to cap
whoismac | Show vendor information and/or download oui reference list
wlancap2wpasec | Upload multiple (gzip compressed) pcapng, pcap and cap files to https://wpa-sec.stanev.org

Read more about new hashcat hash line, here:
https://github.com/hashcat/hashcat/issues/1816#issuecomment-570301203

**Comment by ZerBea** [comment]
I'll check, how we can add 1 & 2 to v6.0.0
Can you please attach the .16800 & .hccapx to see what went wrong in hcxmactool?

**Comment by ChemicalNRG** [comment]
This was the full command i used:
hcxmactool -a PEGATRON --pmkidin=2020-01-02.16800 --pmkidout=PEGATRONCORP.16800

I have attached 2 files that didnt work, 1 extraction from 3 pcapng files and 1 from 5 pcapng. 
[2020-01-02.zip](https://github.com/ZerBea/hcxtools/files/4017386/2020-01-02.zip)

**Comment by ChemicalNRG** [comment]
Sorry, i did forget to add the .hccapx files
Now you have them as well.
Smallest one is from hcxmactool.
[PEGATRON.zip](https://github.com/ZerBea/hcxtools/files/4017413/PEGATRON.zip)

**Comment by ZerBea** [comment]
It took me a while to find the issue.
Please try latest git head and close issue if it works for you.

$ hcxmactool -a PEGATRON --hccapxin=2020-01-02.hccapx --hccapxout=PEGATRON.hccapx
using oui from /home/zerobeat/.hcxtools/oui.txt
82 record(s) read from 2020-01-02.hccapx
4 record(s) written to PEGATRON.hccapx

$ hcxmactool -a PEGATRON --pmkidin=2020-01-02.16800 --pmkidout=PEGATRONCORP.16800
using oui from /home/zerobeat/.hcxtools/oui.txt
515 record(s) read from 2020-01-02.16800
145 record(s) written to PEGATRONCORP.16800

No segmentation fault any longer.

**Comment by ChemicalNRG** [comment]
No faults any longer, thanks for the work you put in it.

I have one other request for hcxcaptool, if i may.
Is it possible to also get some more info about AP's model?
From what i have seen wps info is maybe (at least on newer netgear models) the most informative about that. I dont know if mac address or something else also can be used for that.

**Comment by ZerBea** [comment]
This information can be retrieved by Wireshark.
It is located in
PROBERESPONSE
ASSOCIATIONRESPONSE
REASSOCIATIONRESPONSE
some other frames like ACTION
and
BEACON

**Comment by ZerBea** [comment]
Please let this issue open. It will remind me  to add this to hcxpcapngtool. 
Don't expect useful data here, because many of the VENDORs doesn't use this VENDOR-IEs or fill them with garbage (e.g. 12345678 for the serial number).

**Comment by ZerBea** [comment]
Feature Request 1:
Doesn't make sense.
I'm going to remove most of hcxtools, because they will become obsolete when hashcat 6.0.0 will be released (new hash mode 22000). Only this tools will survive:
hcxdumptool -> WiFi part (fast without additional stuff, able to run headless)
hcxpcapngtool -> conversion (fast, without additional filtering stuff, able to run headless)
hcxhashtool -> provide filter / info about content of hashfile / pre-processor for hashcat/JtR
hcxpsktool -> provide information based on MAC and ESSID
wlancap2wpasec -> upload to data base
hcxwltool -> provide word list functions which other tools don't provide 

Feature Request 2:
Added to hcxhashtool (and several additional filter options).
https://hashcat.net/forum/thread-6661-post-47114.html#pid47114
We use OUI, because some VENDOR names are too long. See:
$ hcxhashtool --vendorlist

Feature Request 3:
Doesn't make sense any longer, because options cascading. You must use each option separate.
Using all options together, the filter will become so strict that you will get no output (hcxhashtool) or the filter became so non-strict, that you have too much uncrackable hashes (hcxpcapngtool).

Also, the few remaining output options to save data, no longer justify the effort to add a prefix.
hcxhashtool:
-i <file>   : input PMKID/EAPOL hash file
-o <file>   : output PMKID/EAPOL hash file
-E <file>   : output ESSID list (autohex enabled)

hcxpcapngtool:
-o <file> : output PMKID/EAPOL hash file
            hashcat -m 22000/22001 and JtR wpapsk-opencl/wpapsk-pmk-opencl
-E <file> : output wordlist (autohex enabled) to use as input wordlist for cracker
-I <file> : output unsorted identity list to use as input wordlist for cracker

I'm not sure on hcxpcapngtool, yet, because not all features are implemented, as of today. If we have more than ten "storing options", I think about to add prefix function.

**Comment by ZerBea** [comment]
Closed, because the issue "segmentation fault" is fixed.

**Comment by ChemicalNRG** [comment]
Only opened again because i wanted to let you know the project iam working on (nothing contributed yet, only description), so you understand why i asked for model info. I didnt see an other way of contacting you.

https://github.com/ChemicalNRG?tab=projects

I do know that it is possible with wireshark, but i like things clean and with as less software as possible, and your software tools are pretty close to an all in package i wanted.
What i wanted to ask also, can your software be used also for wardriving?
I know there is a .nmea output option in the hcxcaptool but i dont think hcxdumptool saves information like best signal and the corresponding coördinates right?

**Comment by ZerBea** [comment]
Ok, good point. Changed head line...

**Comment by ZerBea** [comment]
What i wanted to ask also, can your software be used also for wardriving?
I know there is a .nmea output option in the hcxcaptool but i dont think hcxdumptool saves information like best signal and the corresponding coordinates right?
You are not right: hcxdumptool saves everything. No information get missed here (signal quality, NMEA raw, WLAN traffic, ... everything) 
Than it is up to the evaluation tool to evaluate this data and provide the information you want to have.

**Comment by ZerBea** [comment]
Do not trust in the RSSI values reported by the driver! I compared that values with real measured values (R&S®FSV40) and the result was horrible.
Instead hcxpcangtool will give you a cluster of coordinates and you can select the best one. RSSI values from the driver, stored by hcxdumptool in the pcapng file are ignored.

Also keep in mind:
WiFi traffic is packet oriented. If you have a coordinate with best signal strength, but many signal reflections and phase rotations it will be useless. That coordinate is also useless, if the AP can't here you from there.

Also do not trust in the fairy tails published on several sites:
- high tx power is good
- get exact coordinate by evaluating RSSI from driver

https://github.com/ZerBea/hcxdumptool/issues/80#issuecomment-561126964

**Comment by ZerBea** [comment]
By this commit I started to retrieve device information (AP and CLIENT) from WPS-IE and WMM/WME-IE:
https://github.com/ZerBea/hcxtools/commit/267ed2d7efbc97d531ab1db68e72a8ed41bb8fa0

That has very low priority (SAE and EAP is priority one) and I'm going to add this features step by step.

**Comment by ChemicalNRG** [comment]
Take it slowly, iam already glad you want to do it ;)
Thanks for the start.

**Comment by ZerBea** [comment]
BTW:
If you need this information, tshark and/or Wireshark can do it much better:
$ tshark -r test.pcapng.cap -T fields -e wps.device_name -e wps.serial_number
reference is here:
https://www.wireshark.org/docs/dfref/w/wps.html

But don't expect "amazing results", because many VENDORs doesn't use this fields or fill it with useless information:
https://hashcat.net/forum/thread-6661-post-47483.html#pid47483

**Comment by ZerBea** [comment]
By this commit:
https://github.com/ZerBea/hcxtools/commit/0c532351668411ec5ac7cced6969f4d485df04e5
I started to evaluate WPS-IE from BEACON and PROBERESPONSE frames to retrieve information about the device.
Therefore I added a new option:
`-D <file> : output device information list
`
As first start, we will retrieve MAC_AP, MODELNAME and SERIANLNUMBER (delimited by tab).
More fields will follow, soon.
