### ISSUE TITLE
Is there any way to extract the BSSID of the AP inside a PCAP file? 

### ISSUE THREAD

**Issue by CyrisXD** [ZerBea/hcxtools#126]
I've been looking through these tools but I don't think I can find an answer. I'd love a way to run a command on a .pcap file and log the BSSID of the access point out to the terminal. 

Cheers

**Comment by ZerBea** [comment]
hcxpcapngtool will convert everything (dependent on the used options, which are designed to work on frame parts, e.g. EAPOLTIME, ESSID changes, AKM/cipher suites, replaycounts. This parts are present only in a cap/pcap/pcapng file.
hcxhashtool is working on converted hashfiles and offers all additional options to filter by what you ever want (see hchxastool -h) by part of the hash.
To get hashes from a single AP:
$ hcxpcapngtool -o test.22000 your_pcapfile
$ hcxhashtool --mac-ap=your_mac_ap --info=stdout -i test.22000
That's all.

There is no real need to add full logging capabilities to hcxpcapngtool, because tshark can do this much better. If you need to log all(!) frames related to a special MAC (MAC_AP / MAC_STA), I suggest to use tshark:
$ tshark -r your_pcapfile wlan.addr==your_macap

Knowing about this tools, you have have three choices to get what you want::
log raw content of capture file: tshark
convert to hashes: hcxpcapngtool
filter hashes by options: hcxhashtool

Closed this, because it isn't an issue and the requested feature is already implemented and/or can be done by tshark.
But you can still ask questions, here.
