### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by amansanni** [ZerBea/hcxtools#128]
hcxpcapngtool.c:18:10: fatal error: openssl/sha.h: No such file or directory
   18 | #include <openssl/sha.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

what should i do

**Comment by s77rt** [comment]
Refer to https://github.com/ZerBea/hcxtools/issues/55

**Comment by ZerBea** [comment]
That is a missing dependency. You must install openssl headers.
https://github.com/ZerBea/hcxtools/issues/93
https://github.com/ZerBea/hcxtools/issues/96

From README.md:
`Requirements
--------------
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'
`


Closed this, because it isn't hcxtools issue, but you can still ask your questions here.

**Comment by ZerBea** [comment]
https://github.com/ZerBea/hcxdumptool/issues/101#issuecomment-598068155
