### ISSUE TITLE
Cannot Install libcurl4-openssl-dev

### ISSUE THREAD

**Issue by shakim24** [ZerBea/hcxtools#132]
So I'm trying to install hcxtools through nethunter and I'm having a issue which I've never had before. I get a error saying "unmet dependencies libqt5gui5: Depends: libegl1". I tried installing libegl1 but I falls into a error while processing /var/cache/apt/archives/libegl1_1.3.1-_armhf.deb. All of my files are installed, just this last one is giving me a error.

**Comment by ZerBea** [comment]
That isn't a hcxtools issue. Your installation is broken. There is no such dependency.
https://packages.debian.org/en/sid/libcurl4-openssl-dev

**Comment by ZerBea** [comment]
Closed, but you can still answer questions, here.
I suggest to do a fresh install of your OS.

**Comment by ZerBea** [comment]
Read more about broken packages here:
https://unix.stackexchange.com/questions/389156/how-to-fix-held-broken-packages
here:
https://askubuntu.com/questions/223237/unable-to-correct-problems-you-have-held-broken-packages
here:
https://stackoverflow.com/questions/48431372/removing-broken-packages-in-ubuntu
here:
https://forums.kali.org/showthread.php?27504-E-Unable-to-correct-problems-you-have-held-broken-packages
I recommend to do a fresh install instead of trying to fix this broken packages.

**Comment by ZerBea** [comment]
https://github.com/ZerBea/hcxdumptool/issues/101#issuecomment-598068155
