### ISSUE TITLE
cannot use hcxpcaptool (problems when making)

### ISSUE THREAD

**Issue by Maranzalla** [ZerBea/hcxtools#138]
root@kali:/etc/apt# uname -a
Linux kali 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

When I make I have this:
root@kali:~/hcxtools# make
gcc -O3 -Wall -Wextra -DDOACTIVE -o wlandump wlandump.c -lpcap 
wlandump.c: In function ‘pcaploop’:
wlandump.c:878:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  878 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:906:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  906 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:935:98: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  935 |  sendproberesponse(channel, macf->addr2.addr, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlandump.c:936:73: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  936 |     sendbeacon(channel, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                   ~~~~~~^~~~~~~
wlandump.c:945:104: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  945 | dproberesponse(channel, macf->addr2.addr, zeiger->addr_ap.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlandump.c:946:79: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  946 |       sendbeacon(channel, zeiger->addr_ap.addr, essidf->info_essid_len, essidf->essid);
      |                                                                         ~~~~~~^~~~~~~
wlandump.c:956:95: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  956 |       sendproberesponse(channel, macf->addr2.addr, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~
wlandump.c:957:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  957 |       sendbeacon(channel, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                                ~~~~~~^~~~~~~
wlandump.c:969:94: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  969 |      sendproberesponse(channel, macf->addr2.addr, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                        ~~~~~~^~~~~~~
wlandump.c:970:69: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  970 |      sendbeacon(channel, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                               ~~~~~~^~~~~~~
wlandump.c:974:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  974 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1005:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1005 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1033:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1033 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c: In function ‘setchannel’:
wlandump.c:701:1: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  701 | strncpy(wrq.ifr_name, interfacename , IFNAMSIZ);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -Wall -Wextra -DDOSTATUS -DDOACTIVE -o wlandump-sts wlandump.c -lpcap 
wlandump.c: In function ‘pcaploop’:
wlandump.c:878:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  878 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:906:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  906 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:935:98: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  935 |  sendproberesponse(channel, macf->addr2.addr, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlandump.c:936:73: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  936 |     sendbeacon(channel, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                   ~~~~~~^~~~~~~
wlandump.c:945:104: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  945 | dproberesponse(channel, macf->addr2.addr, zeiger->addr_ap.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlandump.c:946:79: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  946 |       sendbeacon(channel, zeiger->addr_ap.addr, essidf->info_essid_len, essidf->essid);
      |                                                                         ~~~~~~^~~~~~~
wlandump.c:956:95: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  956 |       sendproberesponse(channel, macf->addr2.addr, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~
wlandump.c:957:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  957 |       sendbeacon(channel, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                                ~~~~~~^~~~~~~
wlandump.c:969:94: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  969 |      sendproberesponse(channel, macf->addr2.addr, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                        ~~~~~~^~~~~~~
wlandump.c:970:69: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  970 |      sendbeacon(channel, myaddr.addr, essidf->info_essid_len, essidf->essid);
      |                                                               ~~~~~~^~~~~~~
wlandump.c:974:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  974 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1005:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1005 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1033:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1033 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c: In function ‘setchannel’:
wlandump.c:701:1: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  701 | strncpy(wrq.ifr_name, interfacename , IFNAMSIZ);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -Wall -Wextra -DDOSTATUS -o wlanscan-sts wlandump.c -lpcap 
wlandump.c: In function ‘pcaploop’:
wlandump.c:878:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  878 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:906:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  906 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:974:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  974 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1005:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1005 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1033:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1033 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c: In function ‘setchannel’:
wlandump.c:701:1: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  701 | strncpy(wrq.ifr_name, interfacename , IFNAMSIZ);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -Wall -Wextra -o wlanscan wlandump.c -lpcap 
wlandump.c: In function ‘pcaploop’:
wlandump.c:878:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  878 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:906:70: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  906 |    if(handleapframes(macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                ~~~~~~^~~~~~~
wlandump.c:974:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  974 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1005:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1005 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c:1033:89: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
 1033 | if(handlestaframes(macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid) == FALSE)
      |                                                                                ~~~~~~^~~~~~~

wlandump.c: In function ‘setchannel’:
wlandump.c:701:1: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  701 | strncpy(wrq.ifr_name, interfacename , IFNAMSIZ);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -Wall -Wextra -o wlancapinfo wlancapinfo.c -lpcap
gcc -O3 -Wall -Wextra -o wlancap2hcx wlancap2hcx.c -lpcap
wlancap2hcx.c: In function ‘processcap’:
wlancap2hcx.c:731:110: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  731 | ts.tv_sec, pkh->ts.tv_usec, macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlancap2hcx.c:746:110: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  746 | ts.tv_sec, pkh->ts.tv_usec, macf->addr1.addr, macf->addr2.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlancap2hcx.c:764:110: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  764 | ts.tv_sec, pkh->ts.tv_usec, macf->addr2.addr, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlancap2hcx.c:781:110: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  781 | ts.tv_sec, pkh->ts.tv_usec, macf->addr2.addr, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

wlancap2hcx.c:797:110: warning: taking address of packed member of ‘struct essidinfo’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  797 | ts.tv_sec, pkh->ts.tv_usec, macf->addr2.addr, macf->addr1.addr, essidf->info_essid_len, essidf->essid);
      |                                                                                         ~~~~~~^~~~~~~

gcc -O3 -Wall -Wextra -o wlanhcx2cap wlanhcx2cap.c -lpcap
wlanhcx2cap.c: In function ‘pcapwritepaket’:
wlanhcx2cap.c:153:1: warning: ‘memcpy’ forming offset [26, 32] is out of the bounds [0, 25] of object ‘anonce’ with type ‘const uint8_t[25]’ {aka ‘const unsigned char[25]’} [-Warray-bounds]
  153 | memcpy(&mypacket[pp], anonce, 32);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wlanhcx2cap.c:73:15: note: ‘anonce’ declared here
   73 | const uint8_t anonce[] = {
      |               ^~~~~~
wlanhcx2cap.c:180:1: warning: ‘memcpy’ forming offset [9, 32] is out of the bounds [0, 8] of object ‘snonce’ with type ‘const uint8_t[8]’ {aka ‘const unsigned char[8]’} [-Warray-bounds]
  180 | memcpy(&mypacket[pp], snonce, 32);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wlanhcx2cap.c:77:15: note: ‘snonce’ declared here
   77 | const uint8_t snonce[] = {
      |               ^~~~~~
gcc -O3 -Wall -Wextra -o wlanhc2hcx wlanhc2hcx.c
gcc -O3 -Wall -Wextra -o wlanhcx2essid wlanhcx2essid.c
gcc -O3 -Wall -Wextra -o wlanhcx2ssid wlanhcx2ssid.c
gcc -O3 -Wall -Wextra -o wlanhcx2john wlanhcx2john.c
gcc -O3 -Wall -Wextra -o wlanhcxinfo wlanhcxinfo.c
gcc -O3 -Wall -Wextra -o wlanhcxmnc wlanhcxmnc.c
gcc -O3 -Wall -Wextra -o whoismac whoismac.c -lcurl
gcc -O3 -Wall -Wextra -o pwhash pwhash.c -lcrypto
root@kali:~/hcxtools# make install

so there hcxpcaptool is not working

**Comment by ZerBea** [comment]
You are trying to compile an ancient version of hcxtools. Additional your git clone is completely broken. wlandump was removed a long time ago and is replaced by hcxdumptool:
https://github.com/ZerBea/hcxdumptool

remove your ancient git clone:
$ rm -r hcxtools
now solve the dependencies as described in README.md:
$ sudo apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev

than follow this procedure:
$ git clone https://github.com/ZerBea/hcxtools.git
$ cd hcxtools
$ make
$ sudo make install

output should look like this:

$ git clone https://github.com/ZerBea/hcxtools.git
Cloning into 'hcxtools'...
remote: Enumerating objects: 6466, done.
remote: Total 6466 (delta 0), reused 0 (delta 0), pack-reused 6466
Receiving objects: 100% (6466/6466), 1.94 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (4518/4518), done.

$ cd hcxtools

$ make
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lz -lcrypto -lssl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhashtool.d -o hcxhashtool hcxhashtool.c -lcrypto -lssl -lcurl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpsktool.d -o hcxpsktool hcxpsktool.c -lcrypto -lssl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxwltool.d -o hcxwltool hcxwltool.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlancap2wpasec.d -o wlancap2wpasec wlancap2wpasec.c -lcrypto -lssl -lcurl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/whoismac.d -o whoismac whoismac.c -lcrypto -lssl -lcurl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpmkidtool.d -o hcxpmkidtool hcxpmkidtool.c -lcrypto -lssl -lpthread  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2john.d -o wlanhcx2john wlanhcx2john.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto -lssl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhashcattool.d -o hcxhashcattool hcxhashcattool.c -lcrypto -lssl -lpthread  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxmactool.d -o hcxmactool hcxmactool.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxessidtool.d -o hcxessidtool hcxessidtool.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhash2cap.d -o hcxhash2cap hcxhash2cap.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhc2hcx.d -o wlanhc2hcx wlanhc2hcx.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanwkp2hcx.d -o wlanwkp2hcx wlanwkp2hcx.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcxinfo.d -o wlanhcxinfo wlanhcxinfo.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2ssid.d -o wlanhcx2ssid wlanhcx2ssid.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcxcat.d -o wlanhcxcat wlanhcxcat.c -lcrypto -lssl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanpmk2hcx.d -o wlanpmk2hcx wlanpmk2hcx.c -lcrypto -lssl  -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanjohn2hcx.d -o wlanjohn2hcx wlanjohn2hcx.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlancow2hcxpmk.d -o wlancow2hcxpmk wlancow2hcxpmk.c   -DVERSION_TAG=\"6.0.0\" -DVERSION_YEAR=\"2020\"

$ sudo make install
install -m 0755 -D hcxpcapngtool /usr/local/bin/hcxpcapngtool
install -m 0755 -D hcxhashtool /usr/local/bin/hcxhashtool
install -m 0755 -D hcxpsktool /usr/local/bin/hcxpsktool
install -m 0755 -D hcxwltool /usr/local/bin/hcxwltool
install -m 0755 -D wlancap2wpasec /usr/local/bin/wlancap2wpasec
install -m 0755 -D whoismac /usr/local/bin/whoismac
install -m 0755 -D hcxpmkidtool /usr/local/bin/hcxpmkidtool
install -m 0755 -D wlanhcx2john /usr/local/bin/wlanhcx2john
install -m 0755 -D hcxpcaptool /usr/local/bin/hcxpcaptool
install -m 0755 -D hcxhashcattool /usr/local/bin/hcxhashcattool
install -m 0755 -D hcxmactool /usr/local/bin/hcxmactool
install -m 0755 -D hcxessidtool /usr/local/bin/hcxessidtool
install -m 0755 -D hcxhash2cap /usr/local/bin/hcxhash2cap
install -m 0755 -D wlanhc2hcx /usr/local/bin/wlanhc2hcx
install -m 0755 -D wlanwkp2hcx /usr/local/bin/wlanwkp2hcx
install -m 0755 -D wlanhcxinfo /usr/local/bin/wlanhcxinfo
install -m 0755 -D wlanhcx2ssid /usr/local/bin/wlanhcx2ssid
install -m 0755 -D wlanhcxcat /usr/local/bin/wlanhcxcat
install -m 0755 -D wlanpmk2hcx /usr/local/bin/wlanpmk2hcx
install -m 0755 -D wlanjohn2hcx /usr/local/bin/wlanjohn2hcx
install -m 0755 -D wlancow2hcxpmk /usr/local/bin/wlancow2hcxpmk

now do the same with hcxdumptool:
$ cd
$ git clone https://github.com/ZerBea/hcxdumptool.git
$ cd hcxdumptool
$ make
$ sudo make install

Closed this issue, because it is not related to hcxtools/hcxdumptool, but you can still ask your questions here.
