### ISSUE TITLE
hcxpcapngtool --max-essids

### ISSUE THREAD

**Issue by adrastee** [ZerBea/hcxtools#142]
Hi, 
What's exactly the switch "--max-essids" from hcxpcapngtool ?

> --max-essids=<digit>               : maximum allowed ESSIDs default: 1 ESSID

Does it mean that it will only handle 1 ESSID from the cap file ?
If I have dozens of ESSIDs I need to set --max-essids to 100 or higher?
Thanks.

**Comment by ZerBea** [comment]
```
--max-essids=<digit>               : maximum allowed ESSIDs
                                     default: 1 ESSID
                                     disregard ESSID changes and take ESSID with highest ranking
```

To recover the Pre-Shared Key (PSK) hashcat/JtR have to calculate a PlainMasterKey (PMK) by a function called PBKDF2. This function takes an ESSID and a PSK to calculate the PMK.
During long term captures (24/7) is is possible that the ESSID changed by admin. Additional it is possible that the ESSID is damaged due to receive bit errors. We have seen many submissions on wpa-sec, showing this behavior.
Running default options, hcxpcapngtool will convert the best hash (higest ranking) in combination with the best ESSID (highest ranking) to a hash record, accepted by hashcat/JtR.
Now let us assume the admin changed the ESSID during runtime of hcxdumptool from
default to default1
Running --max-essids=2 it will now convert both ESSIDs (default and default1) for this network instead of only the best one, because we don't know which ESSID is used to calculate the PMK.
max-essids is only useful on really crappy cap/pcap/pcapng files. Normally you don't need this option.

Closed, because it isn't an issue, but you can still ask your questions, here.

**Comment by ZerBea** [comment]
example here:
https://wpa-sec.stanev.org/?search=74b57e0898ec
due to max-essids option wpa-sec (running hcxpcapngtool) was able to recover the PSK at least from one of the ESSIDs.

**Comment by adrastee** [comment]
OK I see, thanks!
