### ISSUE TITLE
hcxpcaptool is missing. Wifite can't make use of the hcxpcaptool because of the .c file not being present

### ISSUE THREAD

**Issue by Joey0538** [ZerBea/hcxtools#158]

**Comment by ZerBea** [comment]
hcxpcaptool is deprecated and was removed from hcxtools by this commit:
b9bd249
It is replaced by hcxpcapngtool and WiFite2 needs an update.
I send a mail to kimocoder to let him know that I started to remove deprecated tools, but you should report your issue here, too:
https://github.com/kimocoder/wifite2/issues

Closed, because it is not and hcxtools issue.
