### ISSUE TITLE
Bug with -A option in wlangenpmkocl

### ISSUE THREAD

**Issue by Mi-Al** [ZerBea/hcxtools#159]
Hello! I use **wlanpmk2hcx** with **wlangenpmkocl** to crack plainmasterkeys.
When I use **wlangenpmkocl** in a command like this:

`maskprocessor '?d?d?d?d?d?d?d?d' | wlangenpmkocl -e ESSID -P 1 -D 0 -a ESSID.pmk`

It works fine.
But if I launch with the **-A** option, I get the empty ESSID.pmk file:

`maskprocessor '?d?d?d?d?d?d?d?d' | wlangenpmkocl -e ESSID -P 1 -D 0 -A ESSID.pmk`

P.S.: I know this report is more suitable for **hcxkeys** repository, but I don’t see the “Issues” button there.

**Comment by ZerBea** [comment]
Issue should be fixed by this commit - thanks for reporting it:
https://github.com/ZerBea/hcxkeys/commit/886696793b1f48ebe422ebe4e4b6db0f40c409c5
```
$ echo "12345678" | ./wlangenpmkocl -e network -A test
running in stdin mode

$ cat test
1fee38d1f1a7319e972b301f18813138d4babda1c46f5e2bfef7442a09a2ffd8:12345678
```

hcxkeys and hcxbtdumptool is more likely a playground. So you're right, there is no issue button.
I think about it to code a tool that calculate a hashcat -m 22000 potfile (as rainbow table). So we can use hashcat --show option on the pre-calculated results. But that is future.
Priority is EAP, SAE (WPA3).

**Comment by Mi-Al** [comment]
It works great now, thank you!
