### ISSUE TITLE
hcxpcaptool replacement

### ISSUE THREAD

**Issue by OscarAkaElvis** [ZerBea/hcxtools#166]
Hi @ZerBea , this is just a question for you or any other administrator of the tool. I'll introduce me. I'm one of the maintainers of the [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon) tool. Since version 10.10 the tool is able to capture PMKID using your tools set.

As far as I know both binaries (`hcxpcaptool` and `hcxpcapngtool`) are included in hcxtools package. At least is that way in the most pentest Linux distros like Kali or Parrot on their latest versions that arrived to that repos (hcxtools 6.0.2).

Somebody told to us [here](https://github.com/v1s1t0r1sh3r3/airgeddon/issues/401) that `hcxpcaptool` is deprecated and now `hcxpcapngtool` will be used instead. I have some doubts and maybe you could help me if you are so kind.

1. From which version the `hcxpcaptool` is retired?

2. The new `hcxpcapngtool`, will still being included in hcxtools package? or it will be another package containing it?

3. I need to know how to perform the same command we are launching now using `hcxpcaptool` but using instead `hcxpcapngtool`. After a hcxdumptool command, we have a .pcapng file. What we need is to transform it into a hashcat (-m 16800) format. The command we are using right now is `hcxpcaptool -z test.16800 test.pcapng`. The final file is test.16800 with hashcat (-m 16800) format. Which is the analogue command to perform the same task using `hcxpcapngtool`? I saw it has no `-z` option. Can you help us on this?

Thank you so much.

**Comment by OscarAkaElvis** [comment]
Regarding question number 3, I did some tests and I think that the replace command for that could be `hcxpcapngtool --pmkid=finaltest.txt test.pcapng`. It seems the resulting file `finaltest.txt` has the old hashcat -m 16800 format and it seems what I'm looking for.

**Comment by R4z0rX** [comment]
> 1. From which version the `hcxpcaptool` is retired?

@OscarAkaElvis I think is 6.1.3. hcxpcaptool was deprecated and removed from hcxtools by this commit: [b9bd249](https://github.com/ZerBea/hcxtools/commit/b9bd249168af21e87598a2c7eda1c9eda7e12b28)

**Comment by ZerBea** [comment]
We added new EAP stuff to hcxdumptool and hcxpcapngtool as well as several new options. It was  easier to rewrite the whole tool as adding the new features to hcxpcaptool. For a transitional period (moving from hash mode 250x/1680x to 2200x) both of them are part of hcxtools. The name was changed from hcxpcaptool to hcxpcapngtool because pcapng is the standard format, now, according to Wireshark/tshark (cap, pcap are very limited and we can't add additional fields to them).

As Wireshark/tshark support cap and pcap, hcxpcapngtool will do this as default, too: 
https://wiki.wireshark.org/Development/PcapNg
`[1.8] - Pcapng is now the default file format.`

The replacement was announced over a long time in README.md and mentioned in changelog:
```
09.10.2020
==========
release v 6.1.3

28.09.2020
==========
removed deprecated wlanpmk2hcx

17.09.2020
==========
release v 6.1.2

10.09.2020
==========
removed deprecated wlanhcx2ssid, wlanhcxinfo aand wlanhcxcat

07.09.2020
==========
removed deprecated wlanhcx2john, wlanjohn2hcx and wlanwkp2hcx

04.09.2020
==========
removed deprecated hcxpcaptool - use hcxpcapngtool instead
```

Please notice. This tools are deprecated, too and I'm going to remove them, soon:
```
| deprecated     | obsolete and - no longer under maintenance - will be removed, soon                                                     |
| -------------- | ---------------------------------------------------------------------------------------------------------------------- |
| hcxmactool     | Various MAC based filter operations on HCCAPX and PMKID files - convert hccapx and/or PMKID to new hashline format     |
| hcxpmkidtool   | CPU based tools to verfiy a PMKID                                                                                      |
| hcxessidtool   | Various ESSID based filter operations on HCCAPX and PMKID files                                                        |
| hcxhashcattool | Convert old hashcat (<= 5.1.0) separate potfile (2500 and/or 16800) to new potfile format                              |
```

BTW:
Hash modes 1680x and 250x are deprecated, too;
```
$ hashcat --help
  22000 | WPA-PBKDF2-PMKID+EAPOL                           | Network Protocols
  22001 | WPA-PMK-PMKID+EAPOL                              | Network Protocols
```

Read more about the new format here:
https://github.com/hashcat/hashcat/issues/1816
and here:
https://github.com/openwall/john/issues/4183
and here:
https://hashcat.net/forum/thread-9506-post-50163.html#pid50163

All state of the art tools should move to the new format.

Closed this report, because it isn't an issue, but you can still ask your questions, here:

**Comment by OscarAkaElvis** [comment]
Thanks for the info. I'll do the needed changes to use the new hash format to be cracked using hashcat -m 22000 instead of -m 16800.

Thanks for all the info.
