### ISSUE TITLE
just run these instructions and it works!

### ISSUE THREAD

**Issue by github765-dev** [ZerBea/hcxtools#177]
git clone https://github.com/ZerBea/hcxtools
git clone https://github.com/ZerBea/hcxdumptool

apt-get install pkg-config
apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev

cd hcxtools
make
make install

cd hcxdumptool
make
make install

**Comment by ZerBea** [comment]
Good point. Additional everyone should know that the driver must support monitor mode, full packet injection and it must accept ioctl() system calls. NETLINK (used by iw) will not work.

Comparison ioctl() vs NETLINK:
https://www.quora.com/What-are-the-differences-between-netlink-sockets-and-ioctl-calls?share=1
```
Kernel services can send information directly to user applications over Netlink, while you’d have explicitly poll the kernel with ioctl functions, a relatively expensive operation.

Netlink comms is very much asynchronous, with each side receiving messages at some point after the other side sends them. ioctls are purely synchronous: “Hey kernel, WAKE UP! I need you to process my request NOW! CHOP CHOP!”

Netlink supports multicast communications between the kernel and multiple user-space processes, while ioctls are strictly one-to-one.

Netlink messages can be lost for various reasons (e.g. out of memory), while ioctls are generally more reliable due to their immediate-processing nature.
```

Conclusion:
```
Control (by hcxdumptool attack vector): 
ioctl should be the first choice, unless there’s an overriding reason, due to its immediacy and reliable delivery.

Data transfer:
For occasional data passing, ioctl should work fine. For bulk data, and especially if you’re look at asynchronous operation, Netlink is preferred.
```

I fully share this point of view. 


Closed, because it is more a recommendation than an issue.
