### ISSUE TITLE
NMEA and CSV output: Segmentation Fault

### ISSUE THREAD

**Issue by nxfxcom** [ZerBea/hcxtools#180]
Hello,

First of all, thank you for your amazing support given that this is open source - you respond faster and better than most commercial support teams :) So if you ever decide to add a donate or buy me coffee button - I am all in! 

Now to my issue, i am trying for the xth time to put together a RasPi running hcxdumptool. Everything works fine, all the tests etc. It captures PMKIDs beautifully and runs smoothly. But the moment I am trying to extract the GPS data with HCXtool I am getting Segmentation Fault. I tried both using --use-gpsd and --use-gps-device. the moment I add to my hcxpcapngtools the --nmea==out.gps portion I get that error. 

What can I share to help me fix this once and for all?

Thank you

**Comment by ZerBea** [comment]
To analyze the issue, I nead the pcapng file.
Please either attach it here, or send it via mail. You can get my mail address from git API.
How to do this is here:
https://www.sourcecon.com/how-to-find-almost-any-github-users-email-address/

**Comment by ZerBea** [comment]
Please also comment output of
$ hcxpcapngtool -v
$ uname -r

hcxpcapngtool should be >= 6.1.5 due to this NMEA fixes:
https://github.com/ZerBea/hcxtools/commit/af901ed6663c4125a14d3190b28ddb3956e09b54
https://github.com/ZerBea/hcxtools/commit/5d8f7afd204705fdd73ba497ce5f6cb9aec02b0c
https://github.com/ZerBea/hcxtools/commit/e59ce621d3a3160c1fe51de41d289e22acc246c4

**Comment by ZerBea** [comment]
Please try latest git head of hcxdumptool and hcxtools.
Issue should be fixed.

**Comment by nxfxcom** [comment]
Danke! It works beautifully now!

**Comment by ZerBea** [comment]
Glad to hear this.
