### ISSUE TITLE
make: pkg-config: No such file or directory

### ISSUE THREAD

**Issue by wolfly22** [ZerBea/hcxtools#189]
I want try hcxtools,
execute
“
git clone https://github.com/ZerBea/hcxtools.git
cd hcxtools
”
is good
but  when  execute“make”， I receive this message:

> wolfly@win10:~/hcxtools$ make
make: pkg-config: 没有那个文件或目录(No such file or directory)
make: pkg-config: 没有那个文件或目录(No such file or directory)
make: pkg-config: 没有那个文件或目录(No such file or directory)
make: pkg-config: 没有那个文件或目录(No such file or directory)
cc -O3 -Wall -Wextra -std=gnu99    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c    -DVERSION_TAG=\"6.1.6-25-ge1cb236\" -DVERSION_YEAR=\"2021\"
hcxpcapngtool.c:6119:1: fatal error: opening dependency file .deps/hcxpcapngtool.d: 权限不够（Insufficient permissions）
 6119 | }
      | ^
compilation terminated.
make: *** 没有规则可制作目标“hcxpcapngtool”，由“build” 需求。 停止。

my  system is  work in  VMware：
Linux win10 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux

what can I do？Thank you for help！

**Comment by ZerBea** [comment]
That is easy to fix. You have to install the missing dependencies (using your packet manager) as described in README.md:
```

Requirements
--------------
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* gcc 10 recommended (deprecated versions are not supported: https://gcc.gnu.org/)
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
* pkg-config installed
To install requirements on Kali use the following 'apt-get install pkg-config libcurl4-openssl-dev libssl-dev zlib1g-dev'
If you decide to compile latest git head, make sure that your distribution is updated on latest version.
```
The names of the packages could be different - that depend on your distribution.

It looks like some distributions (e.g. KALI) doesn't install the dependencies by default.

Closed this issue, because it is not related to hcxtools, but you can still ask your questions here.

BTW:
More information is here:
https://github.com/ZerBea/hcxtools/issues/188
https://github.com/ZerBea/hcxtools/issues/178
https://github.com/ZerBea/hcxtools/issues/174
https://github.com/ZerBea/hcxtools/issues/140
https://github.com/ZerBea/hcxtools/issues/134
