### ISSUE TITLE
[Request] Output diff to file by ESSID or MAC

### ISSUE THREAD

**Issue by dizcza** [ZerBea/hcxtools#214]
I often check new APs in the neighborhood for how secure they are.
But when I dump the wlan traffic to file `b.22000`, I want to get rid of those handshakes from a previous file `a.22000` (and their corresponding APs) that are unbreakable or already found the key with the hashcat. So I'm probing for new APs only.
Currently, the hcxtools does not provide such an option. My workaround is:

```
hcxhashtool -i a.22000 -E a.essid
hcxhashtool -i b.22000 --essid-list=a.essid -o b_old.22000
comm -23 <(sort b.22000) <(sort b_old.22000) > b_new.22000
```

It's hard to remember and I always double-check the hcxhashtool's help before issuing these commands.

I suggest adding the diff option with another file of the same hash type (22000, PMKID, or HCCAPX).

```
--diff=<file>          : output diff to another file by 'MAC:ESSID'
--diff-mac=<file>      : output diff to another file by the MAC only
--diff-essid=<file>    : output diff to another file by the ESSID only
```

Then I could run

```
hcxhashtool -i b.22000 --diff-essid=a.22000 -o b_new.22000
```

**Comment by ZerBea** [comment]
awk can do this much better than I ever can do it:
on MAC AP
$ awk -F'*' 'NR==FNR{c[$4]++;next};c[$4] == 0' <(sort old.22000) <(sort new.22000) > new_mac_ap.22000
on MAC CLIENT
$ awk -F'*' 'NR==FNR{c[$5]++;next};c[$5] == 0' <(sort old.22000) <(sort new.22000) > new_mac_client.22000
on MAC ESSID
$ awk -F'*' 'NR==FNR{c[$6]++;next};c[$6] == 0' <(sort old.22000) <(sort new.22000) > new_essid.22000
or a combination of both.

That can be done e.g. within a script (e.g. diffmac):
```
#!/bin/bash
awk -F'*' 'NR==FNR{c[$4]++;next};c[$4] == 0' <(sort $1.22000) <(sort $2.22000) > $3.22000
wc $3
```

The same applies to perl:
https://stackoverflow.com/questions/30167802/perl-matching-two-columns-from-different-tables

BTW:
Filtering by MAC may not work as expected in case of hcxdumptool attacks against CLIENTs due to hcxdumptool's MAC randomization.

**Comment by ZerBea** [comment]
We decided to switch from binary hccapx to an ASCII format, because that allow  bash tools to work on it.
awk is fine and I use it in several of my scripts to analyze hashes from wpa-sec.

But your idea is good. Let me think about a new tool: hcxdiff
