### ISSUE TITLE
Can't install hcxpcaptool 

### ISSUE THREAD

**Issue by Harshg9653** [ZerBea/hcxtools#217]
Can't install or git clone of hcxpcaptool. This is the last error after this I am able to hack or Crack wifi password.

**Comment by ZerBea** [comment]
hcxpcaptool was replaced by hcxpcapngtool:

Install dependencies (depend on your distribution (see README.md) and do the following steps:
$ rm -r hcxtools
$ git clone https://github.com/ZerBea/hcxtools
$ cd hcxtools
$ make
$ sudo make install
$ hcxpcapngtool --help

Closed, because it is not an issue, but you can still ask your questions here.


BTW:
"Can't install or git clone of hcxpcaptool. This is the last error after this I am able to hack or Crack wifi password."
is too less information to help you.
