### ISSUE TITLE
implicit declaration of function ‘EVP_MAC_init’

### ISSUE THREAD

**Issue by ShutdownRepo** [ZerBea/hcxtools#233]
Same issue as in https://github.com/ZerBea/hcxdumptool/issues/232
On my end, I managed to successfully build from 5937d2ad9d021f3b5e2edd55d79439b8485d3222

**Comment by ZerBea** [comment]
Glad to hear that.
OpenSSL 3.0 marked the old functions (used by hcxdumptool and OpenSSL 1.1) as deprecated. After Arch Linux and Debian bookworm moved to OpenSSL 3.0, I removed the old code from hcxdumptool and hcxtools, too and replaced it by the new EVP API.

More information is here:
implicit declaration of function ‘EVP_MAC_init’

I guess we can close this report, because it is solved after installing OpenSSL 3.0.
