### ISSUE TITLE
Some doubts about using hcxdumptool

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxtools#234]
`hcxdumptool -i wlan0 -o 1.pcapng --active_ beacon --enable_ status=15`

I used this command to capture some handshake packets, but I found the following problems

1. hcxdumptool finds that all the captured handshake packets are stored in a single file. What command do I need to use to store them separately in a single file by (SSID) name in batches ?

2. What command does hcxdumptool need to use to directly save the PCAP format ?

3. How can hcxdumptool capture some hidden AP handshake packets ?

Where can I see examples of these commands? Reference commands are required ?

**Comment by ZerBea** [comment]
"hcxdumptool finds that all the captured handshake packets are stored in a single file. What command do I need to use to store them separately in a single file by (SSID) name in batches ?"

hcxdumptool has three level:
1) receive (capture) everything and transmit (send attack frames) everything.
2) receive (capture) everything and filter transmitted packets only (done by filtermode and filter list options).
3) filter incoming and outgoing traffic - this is done by a Berkeley Packet Filter BPF.
My first answer belongs to level 2.

Here is the answer for level 3:
```
$ sudo hcxdumptool -i <interface> --do_rcascan
to get information about target MAC and operation channel of the target
$ sudo hcxdumptool -m <interface>
set interface to monitor mode
$ sudo tcpdump -i <interface> wlan addr1 11:22:33:44:55:66 or wlan addr2 11:22:33:44:55:66 or wlan addr3 11:22:33:44:55:66 -ddd > attack.bpf
where 11:22:33:44:55:66 is your target MAC.
run hcxdumpttool:
$hcxdumptool -i  <interface> -o dump.pcapng --enable_status=31 --bpfc=attack.bpf
```
Please notice:
When you convert this dump file you receive a warning, because broadcast frames are filtered out and you will loose some interesting frames.
To avoid this, you can expand the filter to:
`$ sudo tcpdump -i <interface> wlan addr1 11:22:33:44:55:66 or wlan addr2 11:22:33:44:55:66 or wlan addr3 11:22:33:44:55:66 or WLAN addr3 ff:ff:ff:ff:ff:ff -ddd > attack.bpf`


`What command does hcxdumptool need to use to directly save the PCAP format ?
`
hcxdumptool use PCAPNG only. Wireshark/tshark (leading analysis tools - that is the reference) use PCPANG as default, too, so there is absolutely no reason to use a limited CAP/PCAP format.

"How can hcxdumptool capture some hidden AP handshake packets ?"
That is mostly a problem of passive dumpers. 
hcxdumptool is interactive and after a while it get the ESSID from the target as described here
https://github.com/ZerBea/hcxtools/pull/210#issuecomment-1107442783

You may have noticed that neither hcxpcapngtool nor hcxdumptool have an option to add add an ESSID by user. That is not necessary.

**Comment by ZerBea** [comment]
BTW:
All this tools are running in background of wpa-sec
https://wpa-sec.stanev.org/?stats
They are not easy to use (some experience is mandatory), but if you know what you're doing, this tools can do magic.

**Comment by ZerBea** [comment]
This is more a discussion than and issue report.
Closed it here and opened discussions here:
https://github.com/ZerBea/hcxdumptool/discussions
