### ISSUE TITLE
setting up GitHub Actions (CI)

### ISSUE THREAD

**Issue by gemesa** [ZerBea/hcxtools#246]
Hi @ZerBea,

I wanted to start a discussion but they are disabled in your repo so created an issue instead. Are you interested in having GitHub Actions set up? In case you are not familiar with them, they are explained [here](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) in detail but in short it is a CI/CD platform that allows you to automate tasks like building and testing of each commit/PR, making your life easier and proving the repo is stable. If you want to use actions in your repo then you need to enable Actions in the repository settings and you need to also add `*.yml` pipelines to the folder `.github/workflows`. These pipelines can be triggered by each push to main and/or each PR (before merging to main). Each pipeline is running on GitHub hosted virtual machines and GitHub Actions usage is free in public repositories.

I have been working on CIs in the following projects for example: [aircrack-ng](https://github.com/aircrack-ng/aircrack-ng) and [8821au-20210708](https://github.com/morrownr/8821au-20210708).

I have a couple of CIs in my mind for your codebase:
- [build CI](https://github.com/morrownr/8821au-20210708/blob/main/.github/workflows/build.yml): this would run a build both with `gcc-11` and `gcc-12`, in your readme I can see you support these versions currently but we can extend it of course
- [codespell CI](https://github.com/morrownr/8821au-20210708/blob/main/.github/workflows/codespell.yml): detects common typos
- [markdown link CI](https://github.com/morrownr/8821au-20210708/blob/main/.github/workflows/markdown-link.yml): detects broken links in your markdown files
- [shellcheck CI](https://github.com/morrownr/8821au-20210708/blob/main/.github/workflows/shellcheck.yml): static analyzer for shell scripts

We can add badges also to your readme something similar to this:

![image](https://user-images.githubusercontent.com/59890178/227783860-b28ff433-3f02-42e5-a7a3-07e426a7527e.png)

In the future we could extend it with other pipelines like checking if the code is formatted properly, unit tests, static code analysis etc.

Let me know if you are interested in this and I can set them up for you.

**Comment by ZerBea** [comment]
Thanks.
This a hobby project and it  should stay that way. I'm not interested in formatting code (I use my own format), code analysis, statistics, logo, icons or anything else.
Please take  a look at my commits:
I add features and functions (and form always follows function), while other developers add beautiful styles (function follows form). 

I do not claim that this code is running on several platforms. 
Recommended platform is Raspberry Pi. recommended OS is Arch Linux  and recommended WiFi chipset is mt76.
Soon hcxdumptool will be replaced by hcxlabtool code, because I decided to go back to the roots:
Discover weak points on WPA-PSK, WPA-PSK256 and WPA-PSK-FT.

BTW:
I opened discussions on hcxdumptool. This can be used an all hcxtools.

**Comment by gemesa** [comment]
I see, lets close this issue then.
