### ISSUE TITLE
always false expression in hcxhashtool and hcxhash2cap

### ISSUE THREAD

**Issue by gemesa** [ZerBea/hcxtools#261]
There is this line both in `hcxhash2cap.c` and `hcxhashtool.c` which is obviously wrong since it is always false:

```
./hcxhash2cap.c:552:	if((lineptr[p +1] == '*') && (lineptr[p +1] == 0)) return 0;
./hcxhashtool.c:1442:	if((lineptr[p +1] == '*') && (lineptr[p +1] == 0)) return 0;
```

```
static uint16_t getfield(char *lineptr, size_t bufflen, uint8_t *buff)
{
...
p = 0;
while((lineptr[p] != '*') && (lineptr[p] != 0) && (p /2 <= bufflen))
	{
	if(! isxdigit((unsigned char)lineptr[p +0])) return 0;
	if(! isxdigit((unsigned char)lineptr[p +1])) return 0;
	if((lineptr[p +1] == '*') && (lineptr[p +1] == 0)) return 0;
	idx0 = ((uint8_t)lineptr[p +0] &0x1F) ^0x10;
	idx1 = ((uint8_t)lineptr[p +1] &0x1F) ^0x10;
	buff[p /2] = (uint8_t)(hashmap[idx0] <<4) | hashmap[idx1];
	p += 2;
	if((p /2) > PMKIDEAPOL_BUFFER_LEN) return 0;
	}
return p /2;
}
```

I just dont see the bigger picture and dont know how to fix it. Maybe it can be even removed.

**Comment by ZerBea** [comment]
Thanks.
It should be :+1: if((lineptr[p +1] == '*') || (lineptr[p +1] == 0)) return 0;
Fixed by this commit:
https://github.com/ZerBea/hcxtools/commit/6989338d4952282306213773266043393a771ce5
Usually we expect the delimiter "*", but it might be possible the the hash line is damaged.Luckily this never happened before.
