### ISSUE TITLE
unable to install i tried everything i could

### ISSUE THREAD

**Issue by D3f4ult-004** [ZerBea/hcxtools#340]
the commands i ran

##################################
apt-get update
apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev
apt-get install libpcap-dev libcurl4-openssl-dev libssl-dev( this command was the 1 i mentioned as different found it in the q&a )
Clone hcxtools from github and compile the binaries:
git clone [https://github.com/ZerBea/hcxtools.git
cd hcxtools
sudo make && sudo make install
##################################
sometimes it reboots and get stuck in the booting process........ It happens only when I try different dependencies commands pls help

![Screenshot 2024-07-25 022031](https://github.com/user-attachments/assets/0efde1b1-b1b3-4940-827b-a3defe02d206)

**Comment by ZerBea** [comment]
You're running KALI Linux, a distribution exclusively for professional penetration testers testers.
hcxdumptool/hcxtools are part of KALI and they can be installed by apt:
https://pkg.kali.org/pkg/hcxdumptool
https://pkg.kali.org/pkg/hcxtools
If you decide to compile them from git, you should know that nearly all development headers to compile programs are not installed by default. It is mandatory to install them using apt.
This is not the case on your system. The openssl header files are not installed and make told you that:
`fatal error: openssl/core.h: No such file or directory`
If you can't install this header files, your KALI version is outdated or your package management system is broken. You have to fix that before you compile hcxdumptool/hcxtools.

I can't help you because I neither use KALI Linux nor recommend to use it: 
https://github.com/ZerBea/hcxdumptool/discussions/418

Closed this report, because this is not a bug in hcxtools.

**Comment by ZerBea** [comment]
You can check the version numbers of installed packages using one of these commands:
https://unix.stackexchange.com/questions/6284/how-do-i-check-package-version-using-apt-get-aptitude
hcxtools need openssl >= 3.0.0

**Comment by rmvfy9nfrf-boop** [comment]
https://github.com/ZerBea/hcxtools.git
