### ISSUE TITLE
Scoring the quality of the pcap file

### ISSUE THREAD

**Issue by g4h4** [ZerBea/hcxtools#344]
Hello,
I'm trying to score/rate the quality of a pcap file using hcxpcapngtool.c output, which is quite verbose with often many warnings.
Kindly let me know if it makes sense?

Simple (but first) algorithm:

Errors: If there's at least one error, the score is set to 1 out of 5.
Warnings:
5 or more warnings: 2/5
3 to 4 warnings: 3/5
1 to 2 warnings: 4/5
No Warnings or Errors: 5/5
if 'very basic format' found, downgrade the score by 1
.
Thanks.

**Comment by ZerBea** [comment]
For several reasons it does not make sense because the warnings are just an information without any ranking.
Absolutely none of this messages (information, warning, error) provide information about the quality of the dump file.

According to your table, If hcxpcapngtool print this warning only, your ranking is 4/5: 
```
Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing/cleaning tool.
```
This is a bug inside the dump tool that prevent that hcxpcapngtool can calculate valid MESSAGE PAIRs.
Usually this dump file is crap and should be deleted!

According to your table, If hcxpcapngtool print this warning only, your ranking is 4/5: 
```
Warning: missing timestamps!
This dump file contains frames with zeroed timestamps.
It prevent calculation of EAPOL TIMEOUT values.
That is a bug of the capturing/cleaning tool.
```
This dump file has been deadly cleaned. It is impossible to calculate EAPOL TIMEOUT values!
Thedump file is crap and should be deleted.

According to your table, If hcxpcapngtool print this warning only, your ranking is 4/5: 
I```
Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead. The PCAP Next Generation dump file format is an attempt to overcome the limitations of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng
```
The RADIOTAP HEADER has been removed by the dump tool or the dump file is cleaned.
The entire information about the quality of the packet (FCS) has been removed and hcxpcapngtool can't detect bad FCS frames any longer, e,g,:
```
frames with FCS (radiotap)...............: 2
frames with correct FCS (crc)............: 2
```
Usually a dump file with too many FCS errors is crap and should be deleted!

According to your table, If hcxpcapngtool print this warning only, your ranking is 4/5: 
```
Warning: too many deauthentication/disassociation frames detected!
That can cause that an ACCESS POINT change channel, reset EAPOL TIMER, renew ANONCE and set PMKID to zero. This could prevent to calculate a valid EAPOL MESSAGE PAIR, to get a valid PMKID or to decrypt the traffic.
```
This warning is related to the workflow and not to the quality of the dump file.
The quality of the dump file might be good, but the workflow prevent to get a valid EAPOL MESSAGE PAIR.

This is an information about the reception quality of the hardware:
```
malformed packets (total)................: 6
BEACON error (total malformed packets)...: 3
IE TAG length error (malformed packets)..: 3
```
It is not covered by your table. If there are a lot of malformed packets, your hardware might be broken.

If you got one of this information, warning or error message, there is something wrong in your work flow or the tools ot the hardware you have used to capture the traffic.
In every case it is a problem and you should fix it immediately!

**Comment by ZerBea** [comment]
I forgot to mention:
If you lower the restrictions by command line options (e.g. --eapoltimeout=, --nonce-error-corrections=, --ignore-ie or --max-essids=) the converted hash file become more and more crappy - even if the quality of the dump file is excellent.

**Comment by g4h4** [comment]
I understand.
Is there no way to programmatically assess/score the output and provide a warning about potential low quality in the hardware or the dump tool? To encourage people to dump again or differently.

**Comment by ZerBea** [comment]
Unfortunately not, because there are too many screws you that can be turned:
capturing tool (limited hardware, bugs, filtering method e.g.  --bpf=, options to lower restrictions e.g. hcxdumptool: --errormax=, workflow eg. transmit thousands of stupid DEAUTHENTICATION frames)
cleaning tool (there is absolutely no need to clean a dump file!)

**Comment by ZerBea** [comment]
A nice example:
record the entire traffic between a CLIENT and an AP via Wireshark.
filter a BEACON and an EAPOL M1 and EAPOL M2 by hand as well as an undirected PROBEREQUEST from the CLIENT which possible contain the PSK in the clear.
save this four packets to a new dump file

The quality of the dump file depends on your skills. If you know what you're doing, the quality of the new file is prefect like the "fifth element". Unfortunately hcxpcapngtool doesn't know about your skills and prints a lot of warnings.
