### ISSUE TITLE
Running make fails

### ISSUE THREAD

**Issue by andydrew23** [ZerBea/hcxtools#69]
Running make when in the hcxtools directory I get an error
Include/gzops.c:1:10: fatal error: zlib.h: No such file or directory
   #include <zlib.h>

**Comment by ZerBea** [comment]
hcxtools are able to handle gz compressed cap files (default  format is pcapng). zlib provide this functions and must be included.
From README.md:
Requirements
Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
libopenssl and openssl-dev installed
librt and librt-dev installed (should be installed by default)
zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
libpthread and pthread-dev installed (used by hcxhashcattool)

To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'

Closed this issue, because it isn't hcxtools related.

**Comment by ZerBea** [comment]
BTW:
I'm very spoiled because I use Arch Linux!
Arch Linux usually just ships "dev files" with the package itself. This costs a bit more disk space for the installation but reduces the number packages you have to manage.
And it's a good distribution for developers. Read more here:
https://dev.to/svettwer/arch-linux-for-devs-26dm
