### ISSUE TITLE
Problem with install/compile

### ISSUE THREAD

**Issue by Mikewins1** [ZerBea/hcxtools#70]
root@KALI:~/hcxtools# make
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1
root@KALI:~/hcxtools# make install
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1

**Comment by neheb** [comment]
Ask Kali to package it for you.

**Comment by Mikewins1** [comment]
With what command?

**Comment by strasharo** [comment]
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'

**Comment by ZerBea** [comment]
Should be inside KALI packaging system:
https://en.kali.tools/all/?category=wireless
https://en.kali.tools/all/?tool=1779

Read more about the requirements and how to satisfy them here:
https://github.com/ZerBea/hcxtools/blob/master/README.md

Why do we need libcrypto:
hcxtools do pre-hashing for hashcat and JtR. We must do this for some kinds of RADIUS hashes.
For upcomming WPA3 we have to add this pre-hashing also to hcxdumptool. Hashcat can't do this pre-hashing, because the results are traffic dependent and we must use them for our requests/responds.
And I like to use this common libs (instead of writing my own), for compatibility reasons with other distros.

Closed this issue, because it isn't hcxtools related.
