### ISSUE TITLE
hcxpcaptool command not found

### ISSUE THREAD

**Issue by ThyMollusk** [ZerBea/hcxtools#75]

**Comment by ZerBea** [comment]
Which distrubution do you use?
Is hcxtools and/or hcxdumptool installed?
Check it:
$ whereis hcxpcaptool
Output should look like this:
hcxpcaptool: /usr/local/bin/hcxpcaptool
If not, it isn't installed.
Is hcxtools and/or hcxdumptool  available via the packet manager of your distribution?
Do a packet search for examle on Arch linux here:
https://www.archlinux.org/
or UBUNUTU here:
https://packages.ubuntu.com/
or on KALI here:
https://www.kali.org/tutorials/finding-packages-for-kali-linux/

To install it manually:
git clone https://github.com/ZerBea/hcxtools
git clone https://github.com/ZerBea/hcxdumptool
git clone https://github.com/ZerBea/hcxkeys
Than cd into the three directories and run make install.
$ cd hcxtools
$ make
$ make install (or, if you are not root; $ sudo make install)
Do the same on the other 2 directories.

If your'e not firm with LINUX read more here:
https://www.lifewire.com/beginners-guide-to-linux-4090233 

Closed this issue, because it is not related to hcxtools.

**Comment by ZerBea** [comment]
It seems that hcxtools is on its way into debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916248
