### ISSUE TITLE
hcxtools/include/gzops.h not found

### ISSUE THREAD

**Issue by OnyxM** [ZerBea/hcxtools#76]
Hi. I've an error while trying to do "make" on hcxtools:
include/gzops.c:1:10: fatal error: zlib.h: Aucun fichier ou dossier de ce type
#include <zlib.h>
Need some help please. I'm using 4.18.0-kali3-amd64

**Comment by ZerBea** [comment]
You must satisfy the dependencies.
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'

from README.me:
Requirements
Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
libopenssl and openssl-dev installed
librt and librt-dev installed (should be installed by default)
zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev libpcap-dev'

Closed, because it isn't a hcxtools issue.

**Comment by ZerBea** [comment]
‎C'était un plaisir d'aider
