### ISSUE TITLE
wlanhcx2cap.c

### ISSUE THREAD

**Issue by KiRanF500** [ZerBea/hcxtools#81]
**root@kali:~/Downloads/hcxtools-master# sudo make**
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpsktool.d -o hcxpsktool hcxpsktool.c -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhashcattool.d -o hcxhashcattool hcxhashcattool.c -lcrypto -lpthread 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhash2cap.d -o hcxhash2cap hcxhash2cap.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhc2hcx.d -o wlanhc2hcx wlanhc2hcx.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanwkp2hcx.d -o wlanwkp2hcx wlanwkp2hcx.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcxinfo.d -o wlanhcxinfo wlanhcxinfo.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2cap.d -o wlanhcx2cap wlanhcx2cap.c -lpcap 
wlanhcx2cap.c:76:28: error: unknown type name ‘pcap_dumper_t’; did you mean ‘pcap_hdr_t’?
 static void pcapwritepaket(pcap_dumper_t *pcapdump, hcx_t *zeigersend)
                            ^~~~~~~~~~~~~
                            pcap_hdr_t
wlanhcx2cap.c: In function ‘writecap’:
wlanhcx2cap.c:270:1: error: unknown type name ‘pcap_dumper_t’; did you mean ‘pcap_hdr_t’?
 pcap_dumper_t *pcapdump;
 ^~~~~~~~~~~~~
 pcap_hdr_t
wlanhcx2cap.c:271:1: error: unknown type name ‘pcap_t’; did you mean ‘eap_t’?
 pcap_t *pcapdh;
 ^~~~~~
 eap_t
wlanhcx2cap.c:291:12: warning: implicit declaration of function ‘pcap_open_dead’ [-Wimplicit-function-declaration]
   pcapdh = pcap_open_dead(DLT_IEEE802_11, 65535);
            ^~~~~~~~~~~~~~
wlanhcx2cap.c:291:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   pcapdh = pcap_open_dead(DLT_IEEE802_11, 65535);
          ^
wlanhcx2cap.c:292:18: warning: implicit declaration of function ‘pcap_dump_open’ [-Wimplicit-function-declaration]
   if((pcapdump = pcap_dump_open(pcapdh, pcapoutstr)) != NULL)
                  ^~~~~~~~~~~~~~
wlanhcx2cap.c:292:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   if((pcapdump = pcap_dump_open(pcapdh, pcapoutstr)) != NULL)
                ^
wlanhcx2cap.c:294:4: warning: implicit declaration of function ‘pcapwritepaket’ [-Wimplicit-function-declaration]
    pcapwritepaket(pcapdump, zeiger);
    ^~~~~~~~~~~~~~
wlanhcx2cap.c:296:4: warning: implicit declaration of function ‘pcap_dump_close’ [-Wimplicit-function-declaration]
    pcap_dump_close(pcapdump);
    ^~~~~~~~~~~~~~~
wlanhcx2cap.c: In function ‘writesinglecap’:
wlanhcx2cap.c:329:1: error: unknown type name ‘pcap_dumper_t’; did you mean ‘pcap_hdr_t’?
 pcap_dumper_t *pcapdump;
 ^~~~~~~~~~~~~
 pcap_hdr_t
wlanhcx2cap.c:330:1: error: unknown type name ‘pcap_t’; did you mean ‘eap_t’?
 pcap_t *pcapdh;
 ^~~~~~
 eap_t
wlanhcx2cap.c:332:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
 pcapdh = pcap_open_dead(DLT_IEEE802_11, 65535);
        ^
wlanhcx2cap.c:333:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
 if((pcapdump = pcap_dump_open(pcapdh, singlecapoutname)) == NULL)
              ^
At top level:
wlanhcx2cap.c:29:31: warning: ‘getreplaycount’ defined but not used [-Wunused-function]
 static unsigned long long int getreplaycount(uint8_t *eapdata)
                               ^~~~~~~~~~~~~~
Makefile:82: recipe for target 'wlanhcx2cap' failed
make: *** [wlanhcx2cap] Error 1

**Comment by ZerBea** [comment]
You're running an old/broken git clone, wlanhcx2cap was removed.
Workaround:
delete hcxtools folder and run a new git clone
git clone https://github.com/ZerBea/hcxtools
then run "make" followed by make install

From the changelog:
02.02.2019
==========
release hcxtools v 5.1.1
removed....: wlanhcx2psk
replaced by: hcxpsktool

removed....: wlanhcx2cap
replaced by: hcxhash2cap
no more libcap dependency!


$ git clone https://github.com/ZerBea/hcxtools
Klone nach 'hcxtools' ...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4073 (delta 2), reused 6 (delta 2), pack-reused 4067
Empfange Objekte: 100% (4073/4073), 1.22 MiB | 1.30 MiB/s, Fertig.
Löse Unterschiede auf: 100% (2847/2847), Fertig.
[zerobeat@tux1 tmp]$ cd hcxtools
[zerobeat@tux1 hcxtools]$ make
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpsktool.d -o hcxpsktool hcxpsktool.c -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhashcattool.d -o hcxhashcattool hcxhashcattool.c -lcrypto -lpthread 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxhash2cap.d -o hcxhash2cap hcxhash2cap.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhc2hcx.d -o wlanhc2hcx wlanhc2hcx.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanwkp2hcx.d -o wlanwkp2hcx wlanwkp2hcx.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcxinfo.d -o wlanhcxinfo wlanhcxinfo.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2cap.d -o wlanhcx2cap wlanhcx2cap.c -lpcap 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2essid.d -o wlanhcx2essid wlanhcx2essid.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2ssid.d -o wlanhcx2ssid wlanhcx2ssid.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcxmnc.d -o wlanhcxmnc wlanhcxmnc.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhashhcx.d -o wlanhashhcx wlanhashhcx.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcxcat.d -o wlanhcxcat wlanhcxcat.c -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanpmk2hcx.d -o wlanpmk2hcx wlanpmk2hcx.c -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanjohn2hcx.d -o wlanjohn2hcx wlanjohn2hcx.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlancow2hcxpmk.d -o wlancow2hcxpmk wlancow2hcxpmk.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/whoismac.d -o whoismac whoismac.c -lcurl 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2john.d -o wlanhcx2john wlanhcx2john.c  
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlanhcx2psk.d -o wlanhcx2psk wlanhcx2psk.c -lcrypto 
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/wlancap2wpasec.d -o wlancap2wpasec wlancap2wpasec.c -lcurl 
$ sudo make install
install -m 0755 -D hcxpcaptool /usr/local/bin/hcxpcaptool
install -m 0755 -D hcxpsktool /usr/local/bin/hcxpsktool
install -m 0755 -D hcxhashcattool /usr/local/bin/hcxhashcattool
install -m 0755 -D hcxhash2cap /usr/local/bin/hcxhash2cap
install -m 0755 -D wlanhc2hcx /usr/local/bin/wlanhc2hcx
install -m 0755 -D wlanwkp2hcx /usr/local/bin/wlanwkp2hcx
install -m 0755 -D wlanhcxinfo /usr/local/bin/wlanhcxinfo
install -m 0755 -D wlanhcx2cap /usr/local/bin/wlanhcx2cap
install -m 0755 -D wlanhcx2essid /usr/local/bin/wlanhcx2essid
install -m 0755 -D wlanhcx2ssid /usr/local/bin/wlanhcx2ssid
install -m 0755 -D wlanhcxmnc /usr/local/bin/wlanhcxmnc
install -m 0755 -D wlanhashhcx /usr/local/bin/wlanhashhcx
install -m 0755 -D wlanhcxcat /usr/local/bin/wlanhcxcat
install -m 0755 -D wlanpmk2hcx /usr/local/bin/wlanpmk2hcx
install -m 0755 -D wlanjohn2hcx /usr/local/bin/wlanjohn2hcx
install -m 0755 -D wlancow2hcxpmk /usr/local/bin/wlancow2hcxpmk
install -m 0755 -D whoismac /usr/local/bin/whoismac
install -m 0755 -D wlanhcx2john /usr/local/bin/wlanhcx2john
install -m 0755 -D wlanhcx2psk /usr/local/bin/wlanhcx2psk
install -m 0755 -D wlancap2wpasec /usr/local/bin/wlancap2wpasec

Closed, because it isn't a hcxtools issue:
