### ISSUE TITLE
is to possible to generate the PMKID from a cap file if the m1 doesn't contain the RSN PMKID ?

### ISSUE THREAD

**Issue by minanagehsalalma** [ZerBea/hcxtools#82]
i have a  cap  file that contains all the 4 way messages ! 
but it doesn't  contain the RSN PMKID ..
is it possible to generate it manually  ?!!!
![image](https://user-images.githubusercontent.com/20546638/52448225-e796df00-2b3b-11e9-902c-bb4bcc9d9aa5.png)

why the rsn is zeros ?

**Comment by ZerBea** [comment]
Some AP's deliver a zeroed PMKID on the first connect attempt, or if the client doesn't requested roaming. In that case the RSN-IE is useless to retrieve the PMKID.
It is not possible to calculate the PMKID for us, because we don't have the plainmasterkey (PMK):
PMKID = HMAC-SHA1-128(PMK, "PMK Name" | MAC_AP | MAC_STA)
The PMK is calculated by PBKDF2:
PMK=PBKDF2( HMAC−SHA1, passphrase, ESSID, 4096, 256) 

It is not mandatory that the PMK is calculated by PBKDF2. PBKDF2 is used on WPA/WPA2 in combination with a passphrase. 
For example on SAE/WPA3 the PMK and PMKID are calculated by this functions:
PMKID = L((commit-scalar + peer-commit-scalar) modulo r, 0, 128)
PMK = KDF-512(keyseed, "SAE KCK and PMK", *(commit-scalar + peer-commit-scalar) modulo r)

**Comment by minanagehsalalma** [comment]
@ZerBea  thanks

**Comment by ZerBea** [comment]
You're welcome.
