### ISSUE TITLE
cant run hcxtools 

### ISSUE THREAD

**Issue by mhzsuraj22** [ZerBea/hcxtools#96]

**Comment by mhzsuraj22** [comment]
While installing hcxtools it says the following error:
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
hcxpcaptool.c:16:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1


also icant seem to install any other package required like 
libopenssl
openssl-dev
libcurl

**Comment by ZerBea** [comment]
Which distribution do you run?
In case of debian based distribution (KALI, UBUNUT) you must install the dev packages!

BTW:
I closed this issue, because it isn't a hcxtools issue.

If you need more informations, follow this issue here:
https://github.com/ZerBea/hcxtools/issues/55

or check the README:
Requirements

    Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
libopenssl and openssl-dev installed
librt and librt-dev installed (should be installed by default)
zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'

**Comment by mhzsuraj22** [comment]
I am running on kali Linux 2019.2
But I cant seem to install those packages 
So would you be kind enough to send me the kali repositories. Bcoz mine doesn't seem to work 
As it cant locate those mentioned packages.

**Comment by ZerBea** [comment]
Did you run:
$ apt get-update
$ apt-get upgrade
$ apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev

BTW:
I can't send you the KALI repositories, because this is the world of Arch Linux here.

**Comment by mhzsuraj22** [comment]
Yeah I ran all the commnds 
All came positive except for that last one 
It just cant locate the package 
Anyways thanks 
I will try more and reply if I found the answer 
Thank you so much for the quick response

**Comment by ZerBea** [comment]
Also I recommend to read this here, if you are a Linux beginner:
https://itsfoss.com/kali-linux-review/

**Comment by ZerBea** [comment]
Ok, please post the error message from apt.

**Comment by ZerBea** [comment]
Both tools came up with KALI:
https://pkg.kali.org/pkg/hcxtools
https://pkg.kali.org/pkg/hcxdumptool

**Comment by DarioMorariu** [comment]
I'm having the exact same problem. I'm using a pwnagotchi.

**Comment by ZerBea** [comment]
@DarioMorariu 
Provided that you're running the latest release v1.5.5:
https://github.com/evilsocket/pwnagotchi/releases/tag/v1.5.5
You should know that the underlying OS (Raspbian lite - based on Debian) is old (Apr 18, 2021).

Latest Raspbian lite version is based on Debian version: 12 (Bookworm - release date: December 11th 2023)
https://www.raspberrypi.com/software/operating-systems/

As mentioned in README.md section requirements, you need  libopenssl >= 3.0 to compile hcxtools.
`* libopenssl (>= 3.0) and openssl-dev installed`

This version is provided by Bookworm:
https://packages.debian.org/bookworm/openssl

Older versions, e.g. Bullseye provide version 1.1.1w only:
https://packages.debian.org/bullseye/openssl
Due to missing functions, you can't compile hcxtools running this old library.

You now have two options:
update to bookworm
or
compile openssl by yourself (I do not recommend this, because you will end  up in a dependency hell)
https://www.openssl.org/

**Comment by ZerBea** [comment]
Also you should know that Debian (and its clones) do not install a development environment by default!

If you decide to compile tools, it is mandatory to install the development environment, the development tools, the header files (-dev packages) and the libraries (linked by hcxtools).
If environment is missing, you'll end up in an ERROR like this one:  fatal error: openssl/sha.h: No such file or directory
