### ISSUE TITLE
error when i make or make install please help

### ISSUE THREAD

**Issue by chiragvshroff** [ZerBea/hcxtools#97]
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99  -MMD -MF .deps/hcxpcaptool.d -o hcxpcaptool hcxpcaptool.c -lz -lcrypto 
In file included from hcxpcaptool.c:36:
include/gzops.c:1:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [Makefile:79: hcxpcaptool] Error 1

**Comment by ZerBea** [comment]
You must install the dev files to satisfy the dependencies. That is not a  hcxtools issue. It depend on your distribution.

Check the README:
Requirements
Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
libopenssl and openssl-dev installed
librt and librt-dev installed (should be installed by default)
zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
libpthread and pthread-dev installed (used by hcxhashcattool)
To install requirements on Kali use the following 'apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev'

Also check this closed issues:
https://github.com/ZerBea/hcxtools/issues/56
https://github.com/ZerBea/hcxtools/issues/55
https://github.com/ZerBea/hcxtools/issues/54

in every case it's related to KALI!



You can still ask questions here, but I'll close this issue, because it is related to your distribution (missing dependencies) and not to hcxtools.

**Comment by ZerBea** [comment]
Which distribution to you run?

**Comment by chiragvshroff** [comment]
@ZerBea kali

**Comment by ZerBea** [comment]
Ok, this may help you finding the packages:
You can find the kali Linux Package Tracker here:
https://pkg.kali.org/

for example search for zlib:
https://pkg.kali.org/pkg/zlib

BTW:
sometimes KALI change package names....

**Comment by ZerBea** [comment]
A good idea is to update the system, before installing new packages:
$ apt get update
$ apt-get upgrade
$ apt-get install libcurl4-openssl-dev libssl-dev zlib1g-dev
